### ISSUE TITLE
Water surface incorrect when spawning underwater

### ISSUE THREAD

**Issue by chipsnapper** [ckosmic/g64#24]
If you spawn Mario while underwater, it will act as if you're currently on the surface, no matter how deep you really are. To fix this you need to either leave the water entirely or swim up to the real surface somehow (ie against a sloped wall)

**Comment by ckosmic** [comment]
Fixed in https://github.com/ckosmic/g64/commit/9e194375d118f7dd5a89532c52f6d99a81364f0d
