### ISSUE TITLE
Mario falsely enters water while paused

### ISSUE THREAD

**Issue by jummy0** [ckosmic/g64#25]
if Mario is moving when the game is paused (easiest to see with shift+tab), and he moves into water, Mario will snap back to his pre-pause position, swimming on land, allowing you to swim into the air as long as you don't press the directional keys.  this is *not* caused by movement interpolation, rather seemingly movement *prediction* continuing while the game is paused.

**Comment by chipsnapper** [comment]
Movement while paused also happens if you pause mid-jump. He snaps back to his pre-pause state once you unpause.

**Comment by ckosmic** [comment]
Water detection fixed in https://github.com/ckosmic/g64/commit/9e194375d118f7dd5a89532c52f6d99a81364f0d and interpolation with the Steam overlay fixed in https://github.com/ckosmic/g64/commit/fc95d503f475829e765420054f9ac5c1b9e09586.
