### ISSUE TITLE
Request: compatibility with ent_create

### ISSUE THREAD

**Issue by jummy0** [ckosmic/g64#27]
currently, `ent_create g64_mario` creates an error sign with Mario's face textures, as it is not bound to a player.  in my opinion, this "null" Mario should bind to the nearest player, allowing basic functionality even in non-Sandbox gamemodes.

**Comment by ckosmic** [comment]
Added in https://github.com/ckosmic/g64/commit/394c0fa861ae61fc816d2277a051f3272f42f46a
