### ISSUE TITLE
"Use" function does not work even when G64 Mario isn't spawned

### ISSUE THREAD

**Issue by opsodps** [ckosmic/g64#29]
It seems like the "use" function (set to E by default) doesn't work, even during normal gameplay when G64 Mario isn't spawned. Disabling the G64 addon allows it to function again. I'm not expecting G64 Mario to be able to use Gmod objects, but I imagine they should be functional when not controlling him.

**Comment by royalcolorwaifu2** [comment]
In Jazztronauts, I can use the map selector, which requires the "use" function, but I cannot sit in the chairs in the bus when it arrives. Every subsequent load also seemed to prevent the cats from spawning in (gonna test this further). I was hoping to use it to more easily check out maps to mess around on as Mario, and play Jazztronauts when I didn't feel like bing bing wahooing at the moment.

**Comment by royalcolorwaifu2** [comment]
Couldn't get the cat spawns to break again.

**Comment by ckosmic** [comment]
Fixed in https://github.com/ckosmic/g64/commit/aeb08be4e48e653efb3c9a4d529f892a3f560317
