### ISSUE TITLE
Unable to pick up health pick ups after removing Mario

### ISSUE THREAD

**Issue by 0x5066** [ckosmic/g64#30]
Before you load Mario into the map, you're able to pick up any health pick ups (Health Vials and Health Kits), after you spawned Mario and then exited him, you're suddenly no longer able to pick up any health pick ups, only when you've died can you pick them up again.

https://user-images.githubusercontent.com/38136789/171987487-1ad97457-46a1-4701-a750-8a46a173609e.mp4

**Comment by ckosmic** [comment]
Fixed in https://github.com/ckosmic/g64/commit/6ed61602191eb42bab3a3cef32bcf0a5ec59afa0 by saving the player's max health
