### ISSUE TITLE
Mario displays incorrectly then map disappears

### ISSUE THREAD

**Issue by fffootloose** [ckosmic/g64#34]
As the title says, when I spawn Mario through the Entities tab, he becomes transparent and several parts of the map disappear.
After a short while, my screen goes fully black until I undo Mario spawning.
The addon has a path to an SM64 US rom and I have made sure I installed the latest binary module and libsm64 correctly.

The map is Half-Life 2 d1_trainstation_01, I've tried it on gm_construct and the only difference is that the screen doesn't go black, every part of the map still disappears. Also Mario's sound effects are extremely loud, is there any way to turn them down? Any help is much appreciated!

Edit: The screen going black only happened on d1_trainstation_01 because all of the map disappeared, leaving only the black void.

**Comment by fffootloose** [comment]
I cloned the repo from github, and it brings up this lua error:

[g64-master] addons/g64-master/lua/autorun/g64_init.lua:433: attempt to call field 'SetGlobalVolume' (a nil value)
    1. v - addons/g64-master/lua/autorun/g64_init.lua:433
        2. unknown - lua/includes/modules/hook.lua:96

**Comment by ckosmic** [comment]
Do you have other addons that may interfering with G64? I haven't gotten any other reports like this and haven't experienced it myself, so it might be an issue specific to the addons you have

**Comment by fffootloose** [comment]
Since my latest post, I have tried disabling all addons except for G64 and it has worked perfectly. Although, I have too many addons to individually look through and disable one by one.

**Comment by ckosmic** [comment]
Interesting. It's most likely some post processing addon or one that messes with the camera. Closing this as it's an addon incompatiblity.
