### ISSUE TITLE
Mario does not play his "eeeyuh" sound when slowly climbing a ledge

### ISSUE THREAD

**Issue by UngoI** [ckosmic/g64#39]
Somehow, this same bug exists in the retro64 minecraft mod. When slowly climbing a ledge (pressing forward instead of jumping) mario has no voiceline, when he is supposed to play this sound (https://themushroomkingdom.net/sounds/wav/sm64/sm64_mario_pulling_up.wav)

**Comment by ckosmic** [comment]
Fixed in https://github.com/ckosmic/libsm64/commit/50367f2e6513697b5e7eb274960054fcaa6cb30b.
