### ISSUE TITLE
Request: cache collision data on disk to reduce load times

### ISSUE THREAD

**Issue by jummy0** [ckosmic/g64#41]
G64 spends a considerable amount of time on each map load to parse the world collision.  On large maps, this can create lagspikes lasting several minutes.  Static props and displacements in particular take the longest.
Caching each map's collision data to a file could alleviate these problems, at the expense of drive space.  The Source Engine does something similar for AI navigation ("Node Graph out of Date, Rebuilding").

**Comment by ckosmic** [comment]
Added in https://github.com/ckosmic/g64/commit/76f0e9bd869726600e48f6b892f361c6f5de59ee and https://github.com/ckosmic/libsm64-gmod/commit/4f20ecc6f7dfc6dce4d315658c1618920f531457. Again, fantastic idea.
