### ISSUE TITLE
After chaning g64_scale_factor, collision with props is disabled

### ISSUE THREAD

**Issue by 0x5066** [ckosmic/g64#48]
As the title suggests, when you change g64_scale_factor, Mario's collision with props is completely disabled, it doesn't matter if Mario was spawned or not.

**Comment by ckosmic** [comment]
This has been fixed in https://github.com/ckosmic/g64/commit/bdefb25218a4196ec00ec222f52026f31d699ca5 and will arrive in the next workshop update
