### ISSUE TITLE
"Disconnect: Client 0 overflowed reliable channel.."

### ISSUE THREAD

**Issue by scarletshadowzz** [ckosmic/g64#53]
I just started using this addon and this occurs every time I load into the map "gm_york_night". I don't know why it happens, but it does. I have reasonable suspicion this is the addon causing it, as this map worked fine without the addon.

**Comment by ckosmic** [comment]
I had a user report that this issue was fixed after I pushed https://github.com/ckosmic/g64/commit/b11063d8ea45b61c609f63829604eed8b8b4e80f. Try checking now to see if it's working for you.
