### ISSUE TITLE
fails to load colision from cache 

### ISSUE THREAD

**Issue by sylveonsylvia** [ckosmic/g64#55]
[G64] Loaded G64 binary module! (Package version 0.1.0)
[G64] Loading map geometry from cache...

[G64] lua/includes/g64_utils.lua:208: attempt to call field 'LoadMapCache' (a nil value)
  1. LoadMapCache - lua/includes/g64_utils.lua:208
   2. InitializeWorld - lua/autorun/g64_init.lua:418
    3. v - lua/autorun/g64_init.lua:440
     4. unknown - lua/includes/modules/hook.lua:96

map tested: gm_constuct

I have no other addons

**Comment by ckosmic** [comment]
This is because you have an outdated libsm64-g64 package.  The latest version will always be here: https://github.com/ckosmic/g64/releases/latest (0.1.1 as of now)

**Comment by sylveonsylvia** [comment]
ah ya that worked 

thank you
