### ISSUE TITLE
Pressing R while in chat removes Mario

### ISSUE THREAD

**Issue by IFerPe** [ckosmic/g64#69]
Despite the update notes saying Mario's inputs don't get registered while in chat or the pause menu, pressing the letter R while in the chat still removes Mario.

**Comment by ckosmic** [comment]
Ah, I forgot about the non-movement keys, thanks

**Comment by ckosmic** [comment]
Fixed in https://github.com/ckosmic/g64/commit/fe923b205426b0bb5124d100d4b777668091197e
