### ISSUE TITLE
G64 - 1.0.0 Mario's eyes are off-centered

### ISSUE THREAD

**Issue by Cjrm550** [ckosmic/g64#70]
what it says on the title, Mario's eyes are a little bit to his right side, I'm 90% sure this wasn't in the previous versions.
![gm_construct0014](https://user-images.githubusercontent.com/109074467/188747564-6ab51bce-beec-4c74-adb4-56de97554fa1.jpg)
![gm_construct0017](https://user-images.githubusercontent.com/109074467/188747566-f80bb18a-2d05-4dff-a845-b0a998664b93.jpg)

**Comment by ckosmic** [comment]
Fixed in https://github.com/ckosmic/g64/commit/c635cfbc411d20fa3abb867d79d88b4915ca694d
