### ISSUE TITLE
An unreasonable amount of time spent in the hooks when the addon isn't even doing anything

### ISSUE THREAD

**Issue by Xenthio** [ckosmic/g64#75]
G64 seems to be taking a majority of the frametime, now this would be fine when mario is spawned and is running around but the addon seems to be taking up a large amount of the frametime while doing absolutely nothing.

**Comment by ckosmic** [comment]
Fixed in https://github.com/ckosmic/g64/commit/6b63298e6acdc6dc9c42fe37d5abad568b1e9583
