### ISSUE TITLE
Lags with giant maps while not even being mario. Note this started to happen when 1.0.0 update released or some bugfix on the addon

### ISSUE THREAD

**Issue by Arthurgamepraix** [ckosmic/g64#76]

**Comment by ckosmic** [comment]
Hi I've pushed an update to the workshop that may have fixed these performance issues, can you confirm it's fixed?

**Comment by Arthurgamepraix** [comment]
Yes its fixed ive noticed that it lagged while playing hl1 source resized maps and other maps but its fixed now
